import type { Metadata } from "next";
import { IBM_Plex_Mono, Inter } from "next/font/google";
import ClerkProvider from "@/providers/ClerkProvider";
import ConvexClientProvider from "@/providers/ConvexProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "./globals.css";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["200", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Application root layout that wraps page content with global fonts and context providers.
 *
 * Renders the top-level html/body structure, applies font CSS variables and "antialiased" to the body,
 * and nests ClerkProvider, ConvexClientProvider, and ThemeProvider around the provided children.
 *
 * @param children - The React node(s) to render inside the provider tree.
 * @returns The root HTML element containing the body and nested providers that wrap `children`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${plexMono.variable} antialiased`}>
        <ClerkProvider>
          <ConvexClientProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}